/* data generated by https://json-generator.com/
    pictures from http://robohash.org/
*/

people = [
  {
    "_id": "5ac594b3b5c4a2dbee486fe7",
    "picture": "http://robohash.org/8c4b1b5a-bb8f-489b-8102-a1e9634627e0",
    "age": 32,
    "name": "Penelope Curtis"
  },
  {
    "_id": "5ac594b3e2f5f6c41ee65ded",
    "picture": "http://robohash.org/4fb7de71-0353-4f52-b1e7-c0f0e727cb4b",
    "age": 29,
    "name": "Tran Barrett"
  },
  {
    "_id": "5ac594b304ba4c9c8730d38d",
    "picture": "http://robohash.org/11d03afc-8796-43f8-b733-12cf2b905cf2",
    "age": 33,
    "name": "Maldonado Espinoza"
  },
  {
    "_id": "5ac594b39a88c61652f27cd4",
    "picture": "http://robohash.org/28d444c8-c5a8-4f8e-8957-e47fcdc4d776",
    "age": 26,
    "name": "Carole Sims"
  },
  {
    "_id": "5ac594b3175d10c1afa8df3f",
    "picture": "http://robohash.org/965a6496-07f1-4e54-9954-fe77c69935d9",
    "age": 30,
    "name": "Stacey Pennington"
  },
  {
    "_id": "5ac594b311c2bfe2f508786e",
    "picture": "http://robohash.org/c649ca37-fc8a-4670-881d-18627caac234",
    "age": 37,
    "name": "Farrell Bradley"
  },
  {
    "_id": "5ac594b34e94d363c3452840",
    "picture": "http://robohash.org/2c4c8865-3f4e-4e58-a84b-59b5acab67c5",
    "age": 34,
    "name": "Bridges Nolan"
  }
]
